Repository laminas/laminas-form, pull requests merged in 2021-05, with the labels that each got.

#105 allow "itemprop", "itemscope" and "itemtype" attributes
  src/View/Helper/AbstractHelper.php
  test/View/Helper/FormInputTest.php
  test/View/Helper/FormTextareaTest.php
Labels: Enhancement

#106 allow inputmode attribute
  src/View/Helper/FormText.php
  src/View/Helper/FormTextarea.php
  test/View/Helper/FormTextTest.php
  test/View/Helper/FormTextareaTest.php
Labels: Enhancement

#81 Adds new property and method hasValue for Laminas\Form\Element
  src/Element.php
  test/ElementTest.php
Labels: Enhancement

#99 Added psalm configuration
  .gitattributes
  composer.json
  psalm-baseline.xml
  psalm.xml.dist
  test/View/Helper/FormCaptchaTest.php
Labels: Enhancement

#110 Mark annotation manager and parser as deprecated for 2.17.0 release
  phpunit.xml.dist
  psalm-baseline.xml
  src/Annotation/AnnotationBuilder.php
  test/Annotation/AnnotationBuilderTest.php
  test/TestAsset/Annotation/EntityWithTypeAsElementName.php
Labels: Enhancement

#114 Normalize composer
  composer.json
Labels: Enhancement

#111 Added support for annotations using doctrine/annotations and removed deprecated code
  composer.json
  docs/book/quick-start.md
  psalm-baseline.xml
  src/Annotation/AbstractAnnotationsListener.php
  src/Annotation/AnnotationBuilder.php
  src/Annotation/AnnotationBuilderFactory.php
  src/Annotation/AnnotationCollection.php
  src/Annotation/ElementAnnotationsListener.php
  src/Annotation/FormAnnotationsListener.php
  src/Annotation/Object.php
  src/Fieldset.php
  src/FieldsetPrepareAwareInterface.php
  src/FormElementManager/FormElementManagerTrait.php
  src/FormElementManager/FormElementManagerV3Polyfill.php
  src/View/HelperConfig.php
  test/Annotation/AnnotationBuilderFactoryTest.php
  test/TestAsset/Annotation/ComplexEntity.php
  test/TestAsset/Annotation/ComplexEntityHydratorV3.php
  test/TestAsset/Annotation/EntityUsingInstanceProperty.php
  test/TestAsset/Annotation/EntityUsingInstancePropertyHydratorV3.php
  test/TestAsset/Annotation/EntityUsingObjectPropertyHydratorV2.php
  test/TestAsset/Annotation/EntityUsingObjectPropertyHydratorV3.php
  test/TestAsset/Annotation/EntityWithHydratorArray.php
  test/TestAsset/Annotation/EntityWithHydratorArrayHydratorV3.php
  test/TestAsset/HydratorAwareModel.php
  test/TestAsset/HydratorAwareModelHydratorV3.php
  test/TestAsset/HydratorStrategy.php
  test/TestAsset/HydratorStrategyHydratorV2.php
  test/View/Helper/CommonTestCase.php
  test/View/Helper/FormCollectionTest.php
  test/View/Helper/FormElementTest.php
  test/View/Helper/FormRowTest.php
  test/_autoload.php
Labels: BC Break, Enhancement

#112 Dropped support for servicemanager 2.x and removed unused dependencies
  composer.json
  docs/book/advanced.md
  psalm-baseline.xml
  src/Annotation/AnnotationBuilder.php
  src/Annotation/AnnotationBuilderFactory.php
  src/ElementFactory.php
  src/FormAbstractServiceFactory.php
  src/FormElementManagerFactory.php
  test/ElementFactoryTest.php
  test/FormAbstractServiceFactoryTest.php
  test/TestAsset/CustomCreatedFormFactory.php
  test/TestAsset/FieldsetWithDependencyFactory.php
Labels: BC Break, Enhancement

#108 render boolean attributes without value for HTML5
  psalm-baseline.xml
  src/View/Helper/AbstractHelper.php
  test/View/Helper/FormInputTest.php
  test/View/Helper/FormTextareaTest.php
Labels: BC Break, Enhancement

#121 PSalm: clear level 7 errors
  psalm-baseline.xml
  psalm.xml.dist
  src/Annotation/AbstractBuilder.php
  src/Fieldset.php
  src/FormElementManager.php
  src/FormFactoryAwareInterface.php
Labels: Enhancement

#125 Replace array|Traversable with iterable type
  docs/book/element/collection.md
  docs/book/element/element.md
  psalm-baseline.xml
  src/Element.php
  src/Element/Captcha.php
  src/Element/Checkbox.php
  src/Element/Collection.php
  src/Element/Csrf.php
  src/Element/DateSelect.php
  src/Element/DateTime.php
  src/Element/DateTimeSelect.php
  src/Element/MonthSelect.php
  src/Element/MultiCheckbox.php
  src/Element/Select.php
  src/ElementInterface.php
  src/Factory.php
  src/Fieldset.php
  src/FieldsetInterface.php
  src/Form.php
  src/InputFilterProviderFieldset.php
  src/LabelAwareInterface.php
  src/LabelAwareTrait.php
  test/Element/CollectionTest.php
  test/ElementTest.php
  test/FieldsetTest.php
  test/TestAsset/ValueStoringFieldset.php
Labels: BC Break, Enhancement

#126 PSalm: clear level 5 errors
  psalm-baseline.xml
  psalm.xml.dist
  src/Element.php
  src/Element/Collection.php
  src/Element/Date.php
  src/Element/DateTime.php
  src/Element/DateTimeLocal.php
  src/Element/Month.php
  src/Element/MultiCheckbox.php
  src/Element/Select.php
  src/Element/Time.php
  src/Element/Week.php
  src/ElementInterface.php
  src/Fieldset.php
  src/Form.php
  src/FormElementManager.php
  src/View/Helper/Captcha/AbstractWord.php
  src/View/Helper/Captcha/Dumb.php
  src/View/Helper/Captcha/Figlet.php
  src/View/Helper/Captcha/Image.php
  src/View/Helper/Captcha/ReCaptcha.php
  src/View/Helper/Form.php
  src/View/Helper/FormCaptcha.php
  src/View/Helper/FormElement.php
  src/View/Helper/FormRadio.php
  src/View/Helper/FormSelect.php
  test/Annotation/AbstractBuilderTestCase.php
  test/Element/CollectionTest.php
  test/FactoryTest.php
  test/FormTest.php
  test/Integration/FormCreatesCollectionInputFilterTest.php
  test/TestAsset/ValidatingModel.php
  test/View/Helper/AbstractCommonTestCase.php
  test/View/Helper/FormCollectionTest.php
  test/View/Helper/FormRowTest.php
  test/View/Helper/FormTest.php
Labels: BC Break, Enhancement

#127 PSalm: clear level 4 errors
  psalm-baseline.xml
  psalm.xml.dist
  src/Annotation/AbstractBuilder.php
  src/Annotation/ElementAnnotationsListener.php
  src/Element.php
  src/Element/Collection.php
  src/ElementInterface.php
  src/Fieldset.php
  src/Form.php
  src/FormElementManager.php
  src/FormInterface.php
  src/LabelAwareInterface.php
  src/View/Helper/Captcha/ReCaptcha.php
  src/View/Helper/FormButton.php
  src/View/Helper/FormCheckbox.php
  src/View/Helper/FormDateTimeSelect.php
  src/View/Helper/FormElementErrors.php
  src/View/Helper/FormMultiCheckbox.php
  src/View/Helper/FormSelect.php
  test/Element/CheckboxTest.php
  test/Element/CollectionTest.php
  test/FormElementManagerTest.php
  test/FormTest.php
  test/Integration/ServiceManagerTest.php
  test/LabelAwareTraitTest.php
  test/View/Helper/Captcha/ImageTest.php
  test/View/Helper/Captcha/ReCaptchaTest.php
  test/View/Helper/FormDateTimeSelectTest.php
  test/View/Helper/FormSelectTest.php
Labels: Enhancement

#123 Update documentation regarding annotations
  docs/book/form-creation/creation-via-factory.md
  docs/book/form-creation/factory-backed-form-extension.md
  docs/book/form-creation/programmatic-form-creation.md
  docs/book/form-creation/using-annotations.md
  docs/book/migration/v2-to-v3.md
  docs/book/quick-start.md
  mkdocs.yml
Labels: Documentation

#131 Require laminas-hydrator:v4
  composer.json
  src/Fieldset.php
  test/Element/CollectionTest.php
  test/FactoryTest.php
  test/FieldsetTest.php
  test/FormAbstractServiceFactoryTest.php
  test/TestAsset/AddressFieldset.php
  test/TestAsset/CategoryFieldset.php
  test/TestAsset/CityFieldset.php
  test/TestAsset/CountryFieldset.php
  test/TestAsset/CreateAddressForm.php
  test/TestAsset/CustomForm.php
  test/TestAsset/NewProductForm.php
  test/TestAsset/OrphansFieldset.php
  test/TestAsset/PhoneFieldset.php
  test/TestAsset/ProductFieldset.php
Labels: Enhancement

#130 Allow name attribute for <fieldset>
  src/View/Helper/FormCollection.php
  test/View/Helper/FormCollectionTest.php
Labels: Bug

#133 Select should accept array as empty option
  src/Element/Select.php
  test/View/Helper/FormSelectTest.php
Labels: Bug

#135 Fieldset: keep null values on bounded object
  src/Fieldset.php
  test/FormTest.php
Labels: Bug

#132 Remove references to Zend aliases and classes
  psalm-baseline.xml
  src/ConfigProvider.php
  src/FormElementManager.php
Labels: BC Break, Enhancement

#136 AbstractHelper: handle null values for boolean attributes
  src/View/Helper/AbstractHelper.php
  test/View/Helper/AbstractHelperTest.php
Labels: Bug

#134 Adds factory for FormElementErrors view helper
  docs/book/helper/form-element-errors.md
  src/ConfigProvider.php
  src/View/Helper/Factory/FormElementErrorsFactory.php
  test/View/Helper/Factory/FormElementErrorsFactoryTest.php
Labels: Enhancement

#118 Elements MonthSelect, DateSelect and DateTimeSelect differentiating between null and empty strings (issue 54)
  src/Element/DateSelect.php
  src/Element/DateTimeSelect.php
  src/Element/MonthSelect.php
  test/Element/DateSelectTest.php
  test/Element/DateTimeSelectTest.php
  test/Element/MonthSelectTest.php
Labels: Enhancement

#138 Element\DateTime is now deprecated
  docs/book/migration/v2-to-v3.md
  src/Element/DateTime.php
  src/View/Helper/FormDateTime.php
Labels: Feature Removal

#98 Adds new method for fieldset class to set hydrator by name
  src/Fieldset.php
  src/Form.php
  test/FieldsetTest.php
  test/FormElementManagerTest.php
  test/FormTest.php
Labels: Documentation Needed, Enhancement

#139 PSalm: clear some level 3 errors
  src/View/Helper/Captcha/AbstractWord.php
  src/View/Helper/Captcha/ReCaptcha.php
  src/View/Helper/Form.php
  src/View/Helper/FormButton.php
  src/View/Helper/FormCaptcha.php
  src/View/Helper/FormCollection.php
  src/View/Helper/FormDateSelect.php
  src/View/Helper/FormDateTimeSelect.php
  src/View/Helper/FormElement.php
  src/View/Helper/FormElementErrors.php
  src/View/Helper/FormInput.php
  src/View/Helper/FormLabel.php
  src/View/Helper/FormMonthSelect.php
  src/View/Helper/FormMultiCheckbox.php
  src/View/Helper/FormRow.php
  src/View/Helper/FormSelect.php
  src/View/Helper/FormTextarea.php
Labels: Enhancement

#140 Fix property types by emulating typed properties
  psalm-baseline.xml
  src/Annotation/AbstractBuilder.php
  src/Element/Captcha.php
  src/Element/Checkbox.php
  src/Element/Collection.php
  src/Element/Color.php
  src/Element/Csrf.php
  src/Element/DateTime.php
  src/Element/Email.php
  src/Element/MonthSelect.php
  src/Element/Number.php
  src/Element/Select.php
  src/Element/Tel.php
  src/Element/Url.php
  src/Factory.php
  src/Fieldset.php
  src/Form.php
  src/FormAbstractServiceFactory.php
  src/FormFactoryAwareTrait.php
  src/View/Helper/AbstractFormDateSelect.php
  src/View/Helper/AbstractHelper.php
  src/View/Helper/FormCollection.php
  src/View/Helper/FormLabel.php
  src/View/Helper/FormMultiCheckbox.php
  src/View/Helper/FormRow.php
Labels: Enhancement

#141 Psalm: clear some level 3 and level 2 errors
  psalm-baseline.xml
  psalm.xml.dist
  src/Annotation/AbstractBuilder.php
  src/Annotation/AnnotationBuilder.php
  src/Annotation/AttributeBuilder.php
  src/Element/Collection.php
  src/Factory.php
  src/Fieldset.php
  src/Form.php
  src/FormAbstractServiceFactory.php
  src/FormElementManager.php
  src/View/Helper/AbstractHelper.php
  src/View/Helper/Captcha/AbstractWord.php
  src/View/Helper/Captcha/ReCaptcha.php
  src/View/Helper/FormCaptcha.php
  src/View/Helper/FormCollection.php
  src/View/Helper/FormElementErrors.php
  src/View/Helper/FormMultiCheckbox.php
  src/View/Helper/FormReset.php
  src/View/Helper/FormRow.php
  src/View/Helper/FormSelect.php
  src/View/Helper/FormSubmit.php
  test/Element/CollectionTest.php
  test/Integration/ServiceManagerTest.php
  test/TestAsset/Entity/Cat.php
  test/View/Helper/Captcha/ReCaptchaTest.php
  test/View/Helper/FormCaptchaTest.php
  test/View/Helper/FormElementErrorsTest.php
Labels: Enhancement
