Repository laminas/laminas-form, pull requests merged in 2021-06, with the labels that each got.

#145 Move FormInterface::setValidationGroup(FormInterface::VALIDATE_ALL) to FormInterface::setValidateAll()
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/quick-start.md
  src/Factory.php
  src/Form.php
  src/FormInterface.php
  test/FormTest.php
Labels: BC Break, Enhancement

#146 Explicit composer.json conflicts for unsupported deps
  composer.json
  phpcs.xml
  psalm-baseline.xml
  src/Annotation/Instance.php
Labels: Enhancement

#148 Updates the page structure and content of the migration guide
  docs/book/v3/form-creation/attributes-or-annotations.md
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/quick-start.md
  mkdocs.yml
Labels: Documentation, Enhancement
