Repository laminas/laminas-form, pull requests merged in 2021-03, with the labels that each got.

#86 Adopt Laminas CI workflow
  .github/workflows/continuous-integration.yml
  .travis.yml
  CHANGELOG.md
  README.md
Labels: Enhancement

#88 Removed duplicate keys
  src/ConfigProvider.php
Labels: Bug

#89 fix Form::getInputFilter() phpdoc return type to match FormInterface
  src/Form.php
Labels: Documentation

#80 Adds page and configuration for installation
  docs/book/application-integration/usage-in-a-laminas-mvc-application.md
  docs/book/installation.md
  mkdocs.yml
Labels: Documentation, Enhancement

#74 Fix documentation bug
  docs/book/application-integration/usage-in-a-laminas-mvc-application.md
Labels: Bug, Documentation, hacktoberfest-accepted

#93 fix: revert bc-break introduced in version 2.16.0
  src/FormElementManager.php
  test/FormElementManagerTest.php
  test/TestAsset/InvokableForm.php
Labels: Bug

#96 Conflict with laminas-code < 3.5 to ensure PHP 8 readiness
  composer.json
Labels: Bug
