Repository laminas/laminas-form, pull requests merged in 2022-10, with the labels that each got.

#189 Add support for PHP 8.2, remove support for PHP 7.4, remove prophecy usage
  .coveralls.yml
  .laminas-ci.json
  composer.json
  composer.lock
  psalm-baseline.xml
  src/Annotation/AnnotationCollection.php
  src/Element/Captcha.php
  src/Element/Collection.php
  src/Factory.php
  src/Fieldset.php
  src/FormElementManager.php
  src/View/Helper/FormButton.php
  src/View/Helper/FormLabel.php
  test/Annotation/BuilderAbstractFactoryTest.php
  test/Element/CheckboxTest.php
  test/Element/ColorTest.php
  test/Element/CsrfTest.php
  test/Element/DateSelectTest.php
  test/Element/DateTest.php
  test/Element/DateTimeLocalTest.php
  test/Element/DateTimeSelectTest.php
  test/Element/DateTimeTest.php
  test/Element/EmailTest.php
  test/Element/MonthSelectTest.php
  test/Element/MonthTest.php
  test/Element/MultiCheckboxTest.php
  test/Element/NumberTest.php
  test/Element/RadioTest.php
  test/Element/RangeTest.php
  test/Element/SelectTest.php
  test/Element/TimeTest.php
  test/Element/UrlTest.php
  test/Element/WeekTest.php
  test/ElementFactoryTest.php
  test/FormElementManagerFactoryTest.php
  test/Integration/ServiceManagerTest.php
  test/View/Helper/AbstractCommonTestCase.php
  test/View/Helper/Captcha/ReCaptchaTest.php
  test/View/Helper/FormCaptchaTest.php
  test/View/Helper/FormElementErrorsTest.php
  test/View/Helper/FormElementTest.php
Labels: Enhancement

#190 Improve type inference for FormElementManager
  psalm-baseline.xml
  src/FormElementManager.php
  test/FormElementManagerTest.php
  test/StaticAnalysis/FormElementManagerType.php
Labels: Documentation, Enhancement

#192 Add internal stub for psr container, updating export-ignores
  .gitattributes
  .psr-container.php.stub
  psalm-baseline.xml
  psalm.xml
  test/TestAsset/CustomCreatedFormFactory.php
  test/TestAsset/FieldsetWithDependencyFactory.php
Labels: Documentation, Enhancement

#195 Updates description for laminas-mvc application integration to simplify the description and usage
  docs/book/v3/application-integration/usage-in-a-laminas-mvc-application.md
Labels: Bug, Documentation

#197 Fix build ?
  test/View/Helper/FormDateTimeSelectTest.php
Labels: Bug
