Repository laminas/laminas-form, pull requests merged in 2023-06, with the labels that each got.

#219 Cache `stripos()` call result when checking for delimiters in a loop
  src/View/Helper/AbstractFormDateSelect.php
  src/View/Helper/FormDateTimeSelect.php
Labels: Enhancement

#214 Removes outdated deprecation messages from documentation for attributes and annotations
  docs/book/v3/form-creation/attributes-or-annotations.md
Labels: Bug, Documentation

#218 Include exclamation point in month element format to prevent time-of-day related bugs
  src/Element/Month.php
  test/Element/MonthTest.php
Labels: Bug

#225 Move array values string type-casting out of the loop
  src/View/Helper/FormSelect.php
Labels: Enhancement

#226 Fix CI Failures with PHPUnit on latest
  composer.json
  composer.lock
  phpunit.xml.dist
  psalm-baseline.xml
  test/Element/CollectionTest.php
Labels: Bug

#227 Accept DateTimeInterface values for Month/Date/DateTime selects
  src/Element/DateSelect.php
  src/Element/DateTimeSelect.php
  src/Element/MonthSelect.php
  test/Element/DateSelectTest.php
  test/Element/DateTimeSelectTest.php
  test/Element/MonthSelectTest.php
Labels: Enhancement

#230 3.13.x ensure numeric expression in datetime select option value for any locale
  src/View/Helper/AbstractFormDateSelect.php
  src/View/Helper/FormDateSelect.php
  src/View/Helper/FormDateTimeSelect.php
  test/View/Helper/FormDateTimeSelectTest.php
Labels: Bug
