Repository laminas/laminas-form, pull requests merged in 2023-11, with the labels that each got.

#244 Add PHP 8.3 support
  .laminas-ci.json
  composer.json
  composer.lock
Labels: Enhancement

#246 General type inference improvements
  psalm-baseline.xml
  src/Element/Collection.php
  src/Fieldset.php
  src/FieldsetInterface.php
  src/Form.php
  test/Element/CollectionTest.php
  test/StaticAnalysis/FormIterableTypes.php
Labels: Documentation, Enhancement

#247 Improve type inference for MultiCheckbox Value Options
  src/Element/MultiCheckbox.php
  test/StaticAnalysis/MultiCheckboxValueOptions.php
  test/View/Helper/FormMultiCheckboxTest.php
  test/View/Helper/FormRadioTest.php
Labels: Documentation, Enhancement

#248 Introduce Form Template to improve inference for processed payloads
  psalm-baseline.xml
  src/Form.php
  src/FormInterface.php
  test/FieldsetTest.php
  test/Integration/TestAsset/Form.php
  test/StaticAnalysis/Asset/ExampleForm.php
  test/StaticAnalysis/Asset/ExampleInputFilter.php
  test/StaticAnalysis/FormTemplates.php
  test/TestAsset/AddressFieldset.php
  test/TestAsset/Annotation/Form.php
  test/TestAsset/BasicFieldset.php
  test/TestAsset/CategoryFieldset.php
  test/TestAsset/CityFieldset.php
  test/TestAsset/CountryFieldset.php
  test/TestAsset/CreateAddressForm.php
  test/TestAsset/CustomCreatedForm.php
  test/TestAsset/CustomForm.php
  test/TestAsset/ElementWithFilter.php
  test/TestAsset/ElementWithStringToArrayFilter.php
  test/TestAsset/FieldsetWithInputFilter.php
  test/TestAsset/FileInputFilterProviderFieldset.php
  test/TestAsset/FileInputFilterProviderForm.php
  test/TestAsset/FormCollection.php
  test/TestAsset/InputFilterProvider.php
  test/TestAsset/InputFilterProviderFieldset.php
  test/TestAsset/InputFilterProviderWithFieldset.php
  test/TestAsset/InvokableForm.php
  test/TestAsset/MyFieldset.php
  test/TestAsset/NestedCollectionsForm.php
  test/TestAsset/NestedFieldset.php
  test/TestAsset/NewProductForm.php
  test/TestAsset/OrphansFieldset.php
  test/TestAsset/OrphansForm.php
  test/TestAsset/ProductFieldset.php
Labels: Enhancement, Review Needed
