Repository laminas/laminas-form, pull requests merged in 2024-01, with the labels that each got.

#254 disable PHPUnits ErrorHandler for LegacyStyleTests
  test/Annotation/AbstractBuilderTestCase.php
Labels: Enhancement

#255 allow disabled- and form-Attribute on fieldsets
  src/View/Helper/FormCollection.php
  test/View/Helper/FormCollectionTest.php
Labels: Enhancement

#256 extract helper functions
  src/View/Helper/AbstractHelper.php
  src/View/Helper/FormButton.php
  src/View/Helper/FormCollection.php
  src/View/Helper/FormLabel.php
  src/View/Helper/FormMultiCheckbox.php
  src/View/Helper/FormRow.php
  src/View/Helper/FormSelect.php
Labels: Enhancement

#258 Fix handling of seconds in the FormDateTimeSelect view helper
  src/Element/Select.php
  src/View/Helper/FormDateTimeSelect.php
  test/View/Helper/FormDateTimeSelectTest.php
Labels: Bug

#257 Add support for exotic locales
  src/View/Helper/FormDateTimeSelect.php
  test/View/Helper/FormDateTimeSelectTest.php
Labels: Enhancement

#260 Improve type inference for FormElementManager::get()
  psalm-baseline.xml
  src/FormElementManager.php
  test/FormElementManagerTest.php
  test/StaticAnalysis/FormElementManagerType.php
Labels: Enhancement

#261 Fix BC break preventing the use of scalar element labels during render
  psalm-baseline.xml
  src/View/Helper/AbstractHelper.php
  test/View/Helper/AbstractHelperTest.php
Labels: BC Break, Bug, Review Needed
